[package]
name = "dql-engine"
edition.workspace = true
license.workspace = true
version.workspace = true
publish = false

[dependencies]
aws-config = "1.8.18"
aws-credential-types = "1.2.14"
aws-sdk-dynamodb = "1.116.0"
aws-sdk-sts.workspace = true
dql-expr = { path = "../dql-expr" }
dql-models = { path = "../dql-models" }
dql-parser = { path = "../dql-parser" }
serde_json = "1"
tokio = { version = "1.52.3", features = ["rt-multi-thread", "macros"] }
