//! Pack `notebook/src/dql_notebook_kernel` (and the Rust example notebook)
//! into the binary so `dqlrs notebook` works after `cargo install`.

use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const KERNEL_FILES: &[&str] = &[
    "__init__.py",
    "__main__.py",
    "install.py",
    "kernel.py",
    "magics.py",
    "progress.py",
    "runner.py",
    "serve_client.py",
];

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let kernel_dir = manifest.join("../../../notebook/src/dql_notebook_kernel");
    let example = manifest.join("../../../notebook/examples/getting-started-rust.ipynb");
    println!("cargo:rerun-if-changed={}", kernel_dir.display());
    println!("cargo:rerun-if-changed={}", example.display());

    if !kernel_dir.is_dir() {
        panic!(
            "dql-cli notebook support needs {} (build from a full dql checkout)",
            kernel_dir.display()
        );
    }

    let mut rust = String::from("// @generated by build.rs — do not edit\n\n");
    rust.push_str("pub static KERNEL_FILES: &[(&str, &str)] = &[\n");
    for name in KERNEL_FILES {
        let path = kernel_dir.join(name);
        println!("cargo:rerun-if-changed={}", path.display());
        let contents = fs::read_to_string(&path)
            .unwrap_or_else(|err| panic!("read {}: {err}", path.display()));
        rust.push_str("    (");
        rust.push_str(&format!("{name:?}"));
        rust.push_str(", ");
        rust.push_str(&format!("{contents:?}"));
        rust.push_str("),\n");
    }
    rust.push_str("];\n\n");

    let example_body = if example.is_file() {
        fs::read_to_string(&example).unwrap_or_else(|err| panic!("read example notebook: {err}"))
    } else {
        String::new()
    };
    rust.push_str("pub const EXAMPLE_NOTEBOOK: &str = ");
    rust.push_str(&format!("{example_body:?}"));
    rust.push_str(";\n");

    let out = PathBuf::from(env::var("OUT_DIR").expect("OUT_DIR")).join("embedded_notebook.rs");
    write_if_changed(&out, &rust);
}

fn write_if_changed(path: &Path, contents: &str) {
    if path.is_file() {
        if let Ok(existing) = fs::read_to_string(path) {
            if existing == contents {
                return;
            }
        }
    }
    fs::write(path, contents).unwrap_or_else(|err| panic!("write {}: {err}", path.display()));
}
